version: '3.8'

services:
  fastapi-app:
    build:
      context: .
    volumes:
      - ./app:/code/app
    ports:
      - "8080:8080" 
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER = ${DB_USER}
      - DB_PWD = ${DB_PWD}
      - DB_HOST = ${DB_HOST}
      - DB_PORT = ${DB_PORT}
      - DB_NAME = ${DB_NAME}
