version: '3.8'

services:
  fastapi-app:
    build:
      context: .
    volumes:
      - ./app:/code/app
    ports:
      - "8080:8080"
    env_file:
      - .env  
    environment:
      - PYTHONUNBUFFERED=1
      - MODE
